apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: frontend
  labels:
    run: frontend  
spec:
  containers:
  - name: frontend
    image: veffhz/hipster-frontend:latest    
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
